name: BuyNova Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Get APK SHA-1
        run: |
          keytool -printcert \
            -jarfile build/app/outputs/flutter-apk/app-release.apk \
            > sha1-full.txt

          echo "================================="
          echo "BUY NOVA APK SHA-1"
          echo "================================="

          grep "SHA1:" sha1-full.txt | tee BuyNova-SHA1.txt

          echo "================================="

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BuyNova-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload SHA-1
        uses: actions/upload-artifact@v4
        with:
          name: BuyNova-SHA1
          path: BuyNova-SHA1.txt
